version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: loositaa/event-booking:latest
    container_name: event-booking
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/event_booking
    depends_on:
      - mongo

volumes:
  mongo-data:

